// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngriinwwvpvhuhsdwcfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ncmlpbnd3dnB2aHVoc2R3Y2ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MzM1MzMsImV4cCI6MjA2MDIwOTUzM30.Llc6uvxfcn5RqAmPZZHyvl1pRCCKDlWd5wWA1lvID5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);